version: '3'

services:
  postgresql:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - "postgres"

  postgres:
    image: 'postgres:13.1'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    ports:
      - "5432:5432"