version: '3'

services:
  postgres:
    image: 'postgres:13.1'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1

  ingest:
    build:
      context: .
      dockerfile: ingest/Dockerfile
    ports:
      - "5010:5010"
    depends_on:
      - "rabbitmq"

  process:
    build:
      context: .
      dockerfile: process/Dockerfile
    depends_on:
      - "rabbitmq"

  status:
    build:
      context: .
      dockerfile: status/Dockerfile
    ports:
      - "5030:5030"
    depends_on:
      - "postgres"

  postgresql:
    build:
      context: .
      dockerfile: postgresql/Dockerfile
    ports:
      - "5050:5050"
    depends_on:
      - "postgres"